---
ansible_python_interpreter: '{{ ansible_playbook_python }}'

# Which operator to test.
operator_under_test: "{{ lookup('env', 'OPERATOR_UNDER_TEST') | default('helm') }}"

# The operator directory inside the testdata/[operator type] directory.
operator_subdir: memcached-operator

# See: https://github.com/operator-framework/operator-sdk-samples/issues/154
app_label_selector: app=memcached

# How many CRs to deploy.
memcached_cr_count: 15

# Options for the Docker images and registry to use.
registry: ttl.sh
image_name: benchmark-operator
image_tag: 1h

# Versions for cluster addons.
cert_manager_version: v0.16.1
prometheus_operator_version: v0.41.1
metrics_server_version: v0.3.7
