---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - config.yml

  tasks:
    - name: Clone the operator-sdk project.
      git:
        repo: https://github.com/alinabuzachis/operator-sdk.git
        version: "benchmark-operator"
        dest: ./operator-sdk
        force: true

    - name: Attempt to fix file permissions.
      file:
        dest: ./operator-sdk
        mode: 0777
        recurse: true

    - name: Deploy a memcached DaemonSet so image is pulled to all nodes.
      include_tasks: tasks/memcached-daemonset.yml

    # - name: Deploy cert-manager (required for Go operator).
    #   include_tasks: tasks/cert-manager.yml
    #   when: "'go' == operator_under_test"

    - name: Build, deploy, benchmark, and undeploy operators.
      include_tasks: tasks/operator-tasks.yml
      loop: ["{{ operator_under_test }}"]
      loop_control:
        loop_var: operator_type
