---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
      - configmaps
      - services
      - endpoints
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - apps
      - apps.openshift.io
    resources:
      - apps
      - deploymentconfigs
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
      - imagestreams
      - routes
      - services
    verbs:
      - '*'
  - apiGroups:
      - apps
    resourceNames:
      - manager-role
    resources:
      - deployments/finalizers
    verbs:
      - update
  ##
  ## Rules for cache.example.com/v1alpha1, Kind: Memcached
  ##
  - apiGroups:
      - cache.example.com
    resources:
      - '*'
    verbs:
      - '*'
#+kubebuilder:scaffold:rules
