---
- name: Prepare host for benchmark.
  hosts: openshift_perftest
  become: true
  
  vars:
   kind_version: v0.11.1
   kubectl_version: v1.21.0
   operator_sdk_version: v1.15.0

  pre_tasks:
    - name: Ensure apt caches are up to date.
      apt:
        update_cache: true

  roles:
    - role: geerlingguy.docker

  tasks:
    - name: Install required packages.
      apt:
        name:
          - golang
          - python3-pip
        state: present

    - name: Install test dependencies.
      pip:
        name:
          - ansible
          - yamllint
          - docker
          - molecule
          - openshift
        state: present

    - name: Download kubectl.
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl
        dest: /usr/bin/kubectl
        mode: 0755

    - name: Download Operator SDK.
      get_url:
        url: "https://github.com/operator-framework/operator-sdk/releases/download/{{ operator_sdk_version }}/{{ item }}-{{ operator_sdk_version }}-x86_64-linux-gnu"
        dest: /usr/bin/{{ item }}
        mode: 0755
      loop:
        - operator-sdk
        - ansible-operator
        - helm-operator

    - name: Download Kind.
      get_url:
        url: https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64
        dest: /usr/bin/kind
        mode: 0755

- name: Run benchmark.
  hosts: openshift_perftest
  become: true

  tasks:
    #- name: Clone benchmark-operator-ocp project.
    #  git:
    #    repo: https://github.com/alinabuzachis/benchmark-operator-ocp.git
    #    version: main
    #    dest: ~/benchmark-operator-ocp

    - name: Run molecule test scenarios.
      command: molecule test
      args:
        chdir: ~/benchmark-operator-ocp
      environment:
        OPERATOR_UNDER_TEST: "{{ item }}"
      register: molecule_result
      tags: ['molecule']
      loop:
        - ansible
        - go
        - helm
    
    - name: Pause to allow to get results.
      pause:
        seconds: 20

    - name: Store results in a local result file.
      copy:
        content: "{{ item.stdout }}"
        dest: "./result-{{ item.item }}-{{ ansible_date_time }}.txt"
        mode: 0664
      loop: "{{ molecule_result.results }}"
      delegate_to: localhost
      no_log: true
      become: false
      tags: ['molecule']
